-- Create the USERS table
CREATE TABLE USERS (
    USER_ID    NUMBER PRIMARY KEY,
    USERNAME   VARCHAR2(100) NOT NULL,
    EMAIL      VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD   VARCHAR2(255) NOT NULL,
    ROLE       VARCHAR2(50) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);
  
-- Create a sequence for USER_ID
CREATE SEQUENCE USERS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;