BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "PRODUCTS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "STORES" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "CLOTHING_LOOKUP" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "COLOR_LOOKUP" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "CUSTOMERS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "DEPARTMENTS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "DEPARTMENT_LOOKUP" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "EMPLOYEES" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "ORDERS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "ORDER_ITEMS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE "PROJECTS" CASCADE CONSTRAINTS';

    -- Views

    EXECUTE IMMEDIATE 'DROP VIEW "CUSTOMER_ORDER_PRODUCTS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP VIEW "EMP_V" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP VIEW "PRODUCT_ORDERS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP VIEW "PRODUCT_REVIEWS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP VIEW "STORE_ORDERS" CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP VIEW "STORE_ORDERS_STATUS" CASCADE CONSTRAINTS';
END;
